### ISSUE TITLE
Switching to Nvidia puts me in a log in loop on Archcraft

### ISSUE THREAD

**Issue by xQzca** [geminis3/envycontrol#10]
When I use this (also with optimus manager) I get put into a login loop where when I try to login (SDDM) it goes to a black screen and puts me on the login screen again.

specs

os: archcraft
wm: openbox
dm: sddm
cpu: i5 9300h
gpu: gtx 1650 mobile

**Comment by xQzca** [comment]
going to a terminal before login and switching back to integrated allows me to log in, i have nvidia drivers installed aswell

note: this also happened with optimus manager

**Comment by geminis3** [comment]
Hello there, please send me the output of the `lspci` command as well as the Nvidia driver version.

Thanks.

**Comment by DaVikingMan** [comment]
I also had this issue with optimu-manager. Do you have a file called xorg.conf or have you ran nvidia-xconfig as that command sometimes incorrectly sets the display names and ids. If yes, then I recommend to delete the file and try again(file path=/etc/X11/xorg.conf).

**Comment by xQzca** [comment]
i dont know what happened, but after booting my laptop the next day, it seems to have fixed itself and seems to be working fine
