### ISSUE TITLE
Switching to nvidia graphics breaks sddm and xorg

### ISSUE THREAD

**Issue by DaVikingMan** [geminis3/EnvyControl#2]
After running sudo envycontrol --switch nvidia and rebooting, sddm doesn't start and nor does xorg(By doesn't start I mean that the only thing that is displayed on the screen is a flashing white underscore)

Steps to reproduce:

1. Switch to nvidia graphics
2. Reboot

Steps to fix the problem : 

1. Switching back to hybrid graphics worked for me. You might have to remove the package if that didn't fix the problem.

**Comment by geminis3** [comment]
What distro are you using? thank you!

**Comment by DaVikingMan** [comment]
EndevourOs(based on arch linux)

**Comment by geminis3** [comment]
> EndevourOs(based on arch linux)

I have added an additional script that performs some necessary xrandr operations before the initialization of SDDM when on Nvidia mode (the same also applies to LightDM), EnvyControl should automatically detect your Display Manager and setup the script if applicable.

If the user doesn´t has systemd then the Display Manager should be specified manually using the --dm argument.

Can you give it a try? you can clone this repo and run `git checkout sddm` then execute EnvyControl with `sudo python envycontrol.py --switch nvidia`.

https://github.com/geminis3/EnvyControl/tree/sddm

Thank you!

**Comment by geminis3** [comment]
I successfully tested the latest changes from a live Manjaro KDE session, Nvidia mode is working as expected after restarting the display manager.

![PXL_20211221_211357164.jpg](https://user-images.githubusercontent.com/49411169/147023519-a2ac8b5d-96ec-4d60-9fce-e74e9e84fd9b.jpg)

**Comment by geminis3** [comment]
Also working on Manjaro Xfce live session (it uses LightDM)

![PXL_20211221_212137216.jpg](https://user-images.githubusercontent.com/49411169/147024161-40a9b07e-964f-447f-8754-59a591aebf11.jpg)

**Comment by DaVikingMan** [comment]
Yeah, my system booted perfectly with xorg and sddm working as expected. Thanks!

**Comment by geminis3** [comment]
> Yeah, my system booted perfectly with xorg and sddm working as expected. Thanks!

Thank you, tomorrow I will merge those changes into main and update the AUR package.
