### ISSUE TITLE
no display on external monitor

### ISSUE THREAD

**Issue by r18duarte** [geminis3/envycontrol#22]
Basic info first

-  Linux distro: Archcraft
-  Linux kernel: 5.16.10-arch1-1
- Desktop environment: OpenBox
- Display manager: SDDM
- Driver version: Nvidia 510.54
- EnvyControl version: EnvyControl 1.3
- System: MSI GS65 9SD (i7-9750H and 1660ti)

now to the issue:
my laptop has a power led that is white when nvidia gpu is off and orange when it's powered on and it's controlled by the BIOS.

when in integrated mode it really turns my nvidia gpu off, led goes white and is fine, but when in hybrid mode it turns the dGPU on and the led goes orange but i can't get display out of my laptop, but when on nvidia mode it does work but i only have image on my external monitor. Is this a limitation from linux or it is possible to fix this in order to have it working "as intended" (like optimus on windows)

second issue:
cant switch from integrated to nvidia directly, it errors out saying no nvidia gpu is available but i was reading on this and it's because the gpu wasn't powered on on the last shutdown, possibily can't get fixed but i can live with it.

**Comment by r18duarte** [comment]
checking in 2h later to say i'm a dummy, was trying to get optimus working with bumblebee, forgot to remove it, removed all packages related to optimus that i had installed previously, fully working now. second issue it is what it is, can live with it.

**Comment by geminis3** [comment]
Hello there, the second issue you describe was introduced since dynamic
Nvidia GPU detection was added because the PCI Bus ID isn't 01:00:00 on all
laptop models out there so you need to switch to hybrid first, restart and
then Nvidia mode.

Greetings.
