### ISSUE TITLE
Unable to switch to nvidia only on wayland

### ISSUE THREAD

**Issue by ShabirK21** [geminis3/envycontrol#23]
I am running Arch Linux with KDE, running wayland on RTX 3070 laptop gpu, when i run "sudo envycontrol --switch nvidia", it asks me to reboot to change, which i do. But under settings the graphics processer is still my AMD iGPU, while on envycontrol shows nvidia.

**Comment by DaVikingMan** [comment]
What's the output of `glxinfo | grep "OpenGL vendor string"`?

**Comment by ShabirK21** [comment]
Sorry for the late reply. 
![Screenshot_20220225_133113](https://user-images.githubusercontent.com/67749458/155659700-62132707-673c-4a51-bdb4-99e052f83c62.png)

**Comment by geminis3** [comment]
> I am running Arch Linux with KDE, running wayland on RTX 3070 laptop gpu, when i run "sudo envycontrol --switch nvidia", it asks me to reboot to change, which i do. But under settings the graphics processer is still my AMD iGPU, while on envycontrol shows nvidia.

Nvidia only mode is X.org only, there isn't such thing on Wayland unless your laptop has a graphics mux.

**Comment by Hazem42** [comment]
Will this ever be a thing? (NVIDIA only mode on Wayland)
I mean NVIDIA already works fine under Wayland so why not?

**Comment by bayasdev** [comment]
When pigs fly or when Nvidia fixes their mess, I'm not sure what will
happen first.

**Comment by D3vil0p3r** [comment]
> Will this ever be a thing? (NVIDIA only mode on Wayland) I mean NVIDIA already works fine under Wayland so why not?

Use nvidia-exec package (nvx binary) for switching GPU in Wayland.

**Comment by bayasdev** [comment]
> > Will this ever be a thing? (NVIDIA only mode on Wayland) I mean NVIDIA already works fine under Wayland so why not?
> 
> Use nvidia-exec package (nvx binary) for switching GPU in Wayland.

Nice, did Nvidia actually implemented true dmabuf support?

PD: I have been out of the loop for a while since I switched to Mac :S

**Comment by D3vil0p3r** [comment]
Not sure if they are implemented dmabuf support. I used nvidia-exec a lot of time on Wayland and it seems to work. I opened a feature request on https://github.com/bayasdev/envycontrol/issues/113 for keeping trace ^^

PS: thank you for this tool. Better than optimus manager.
