### ISSUE TITLE
Revert EnvyControl changes

### ISSUE THREAD

**Issue by FPuoti255** [geminis3/envycontrol#24]
I'd like to remove envycontrol due to the little bug when connecting HDMI while using wayland (GNOME).
I've uninstalled it while in hybrid mode, but it seems that wayland still crashes when HDMI is connected.
How can I solve this issue?

**Comment by geminis3** [comment]
It's caused by Nvidia drivers, it also happens to me.

See relevant GNOME bug report:

https://gitlab.gnome.org/GNOME/mutter/-/issues/1891

**Comment by FPuoti255** [comment]
It is not true, because now I'm using the nvidia driver 510, not the 470, and this problem has been solved.
I'm using endeavourOS and after a fresh install wayland does not crash when plugging the HDMI in
