### ISSUE TITLE
Envycontrol does not work on Clear Linux v35000

### ISSUE THREAD

**Issue by tur1ngb0x** [geminis3/envycontrol#27]
Details:
* CPU: Intel i5 8250U
* GPU: Intel UHD 620 + Nvidia MX150
* Distro: Clear Linux Desktop v35000 (GNOME)

Description:
* Envycontrol fails to switch gpu mode on Clear Linux v35000.
* After manually creating `/etc/modprobe.d` folder, it works as expected.

Steps:
* `git clone https://github.com/geminis3/envycontrol.git`
* `cd envycontrol`
* `sudo python ./envycontrol.py --switch integrated`

Error:
* cannot find file /etc/modprobe.d/blacklist-nvidia.conf

Fix:
* `sudo mkdir -pv /etc/modprobe.d`
* `sudo python ./envycontrol.py --switch integrated`

Suggestions:
* During GPU switching, check if `/etc/modprobe.d` exists.
* If it does not, create the directory explicitly.

**Comment by geminis3** [comment]
Should be fixed on latest main, thanks for your report.
