### ISSUE TITLE
Update 2.0: Nvidia mode not bootable with amd/nvidia configurations

### ISSUE THREAD

**Issue by cronyakatsuki** [geminis3/envycontrol#33]
Distro: Arch Linux
Kernel: 5.17.1-zen1-1-zen
WM: BSPWM, startx
Nvidia version: 510.60.02
Envycontrol version: 2.0

With  the new 2.0 update the nvidia mode won't boot with amd/nvidia hardware. (I use startx and automatic login and startup so it just goes and restarts xorg without stopping)

[pastebin](https://pastebin.com/yRaRVEsc) for the xorg log file.

**Comment by geminis3** [comment]
@cronyakatsuki can you check if using amdgpu instead of modesetting driver on `/etc/X11/xorg.conf` fixes your issue?

Greetings.

**Comment by cronyakatsuki** [comment]
Already check but it doesn't fix it

**Comment by cronyakatsuki** [comment]
@geminis3 I have found the culprit.
Amd user need to have the xrandr script run or they won't get script output unlike the intel users.
This means that there is still a need to set the xrandr script with either modeset when using the modesetting driver or getting the name oft the amd igpu from xrandr and setting it with it like I did in my fork.

**Comment by geminis3** [comment]
@cronyakatsuki can you check if removing `/etc/X11/xorg.conf` and creating `/etc/X11/xorg.conf.d/10-nvidia.conf` with the following content just works without additional setup?

```
Section "OutputClass"
    Identifier "nvidia"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
    Option "AllowEmptyInitialConfiguration"
    Option "IgnoreDisplayDevices" "CRT"
    Option "PrimaryGPU" "Yes"
    ModulePath "/lib/x86_64-linux-gnu/nvidia/xorg"
EndSection
```

**Comment by cronyakatsuki** [comment]
> @cronyakatsuki can you check if removing `/etc/X11/xorg.conf` and creating `/etc/X11/xorg.conf.d/10-nvidia.conf` with the following content just works without additional setup?
> 
> ```
> Section "OutputClass"
>     Identifier "nvidia"
>     MatchDriver "nvidia-drm"
>     Driver "nvidia"
>     Option "AllowEmptyInitialConfiguration"
>     Option "IgnoreDisplayDevices" "CRT"
>     Option "PrimaryGPU" "Yes"
>     ModulePath "/lib/x86_64-linux-gnu/nvidia/xorg"
> EndSection
> ```

No it doesn't regretfully. I also checked just now and sddm and lightdm were just showing a black screen when using either modesetting or amdgpu in nvidia mode.

**Comment by geminis3** [comment]
@cronyakatsuki can you post the script that works for your AMD + Nvidia config?

**Comment by cronyakatsuki** [comment]
@geminis3 this is the script

```
xrandr --setprovideroutputsource "AMD Radeon Vega 8 Graphics @ pci:0000:05:00.0" NVIDIA-0
xrandr --auto
```
Amd radeon name depends on the name you get from xrandr --listproviders. 

> example
```
Providers: number : 2
Provider 0: id: 0x54 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 4 outputs: 2 associated providers: 0 name:AMD Radeon Vega 8 Graphics @ pci:0000:05:00.0
Provider 1: id: 0x1f5 cap: 0x0 crtcs: 0 outputs: 0 associated providers: 0 name:NVIDIA-G0
```
