### ISSUE TITLE
Switching to Nvidia displays black screen and other misc. issues

### ISSUE THREAD

**Issue by JDar2K** [geminis3/envycontrol#34]
```bash
Operating System: EndeavourOS
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.17.1-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 16 × Intel® Core™ i7-10875H CPU @ 2.30GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Graphics Processor: NVIDIA GeForce RTX 2060 with Max-Q Design/PCIe/SSE2
``` 
I'm having an issue similar to #33, but with Intel/Nvidia. 
When switching to Nvidia and rebooting, the screen turns black and I need to Shift+Alt+F2 to switch back to hybrid.
That being said I tested my system with Optimus-Manager and had no issues and my problem with transparency in KDE were fixed.

**Comment by cronyakatsuki** [comment]
This all probably because the xrandr script is not run anymore so the display manager can't setup the xorg correctly.

**Comment by cronyakatsuki** [comment]
@geminis3 I reimplemented it with in my fork, plus did the amd tearing fix and it seems to work on my system with no problem.
Will do a pull request so check it.
