### ISSUE TITLE
LightDM fails to start after switching modes

### ISSUE THREAD

**Issue by lvctr** [geminis3/envycontrol#38]
Everytime I switch modes, LightDM fails to start, and checking systemd status tells me it's because `start request repeated too quickly`.

I need to switch to another TTY and manually start LightDM every time.

I have tried manually setting my DM (using `--dm lightdm`) to no avail.

I use a Lenovo Legion 5 15ARH05 with a 4800H (RX Vega 7) + GTX 1650 Ti. OS is Arch Linux.

If anyone can help that would be great. I can also provide additional information if required. Thanks!

**Comment by DaVikingMan** [comment]
Did you try the fixes mentioned here(https://github.com/DaVikingMan/EnvyControl/wiki/Fixes-for-some-common-problems, the third fix)?

**Comment by lvctr** [comment]
The afformentioned fixes did not work for me.
As for the Arch link, I use `lightdm-webkit2-greeter` and it was not removed from my system.
I have tried reinstalling LightDM and the greeter and such to no avail.

**Comment by lvctr** [comment]
I've done some further testing and it seems it only happens when I switch to integrated mode. When I switch back to hybrid mode it works fine.

**Comment by DaVikingMan** [comment]
Do any other login managers work?

**Comment by lvctr** [comment]
Hi, I seem to be able to have fixed this by setting `logind-check-graphical=true` in `/etc/lightdm/lightdm.conf`.

Sorry for the inconvenience!
