### ISSUE TITLE
Envycontrol doesn't remove iGPU when set to nvidia

### ISSUE THREAD

**Issue by DaVikingMan** [geminis3/envycontrol#40]
Envycontrol doesn't remove the integrated gpu when it's set to nvidia mode. This can be seen in vulkaninfo(which still has intel gpu registered) and also in neofetch output. 
This also causes screen tearing and in some cases, input lag and also messes up some of the vsync settings(for example, when in hybrid mode the fps is locked to the refresh rate but when switched to nvidia, it isn't which I think is due to this as it only sets it as default but doesn't remove the igpu)

**Comment by DaVikingMan** [comment]
The issue with vkcube seems to have been caused due to intel video drivers, which was fixed after using modesettings driver. I will also add the same to the wiki page if others were to encounter the same issue

**Comment by geminis3** [comment]
Disabling iGPU will lead to no video output on screens connected to iGPU even if it's used as an output sink (Nvidia mode), the only way to disable iGPU is from BIOS on laptops that have a MUX switch onboard (such as Clevo and Lenovo Legion models).
