### ISSUE TITLE
Nvidia and hybrid mode issues

### ISSUE THREAD

**Issue by Lithi27** [geminis3/envycontrol#51]
From what I can tell, it doesn't load up x org server when i switch to nvidia, also games (in this case "payday 2") don't launch in hybrid mode

Distro: Fedora 36
kernel version and type: 5.18.9-200.fc36.x86_64
nvidia graphics card: geforce 940mx
nvidia driver version: 515.57
intel integrated graphics: Intel HD Graphics 620
EnvyControl version: 2.1.1

If i need to include more information here, please tell me.
Edit: so i just ran nvidia-xconfig and i got these errors

WARNING: Unable to locate/open X configuration file.

WARNING: Unable to parse X.Org version string.

ERROR: Unable to find any GPUs in the system.

ERROR: Unable to write to directory '/etc/X11'.

**Comment by DaVikingMan** [comment]
While switching to hybrid, type N when prompted to turn on RTD3 power management

**Comment by Lithi27** [comment]
> While switching to hybrid, type N when prompted to turn on RTD3 power management

that's nice but what about the errors and warnings? i also have very few options in nvidia settings and it gives me these errors when i run the command `nvidia-settings`

ERROR: NVIDIA driver is not loaded

(nvidia-settings:4179): GLib-GObject-CRITICAL **: 07:21:53.240: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

** (nvidia-settings:4179): CRITICAL **: 07:21:53.242: ctk_powermode_new: assertion '(ctrl_target != NULL) && (ctrl_target->h != NULL)' failed

**Comment by Lithi27** [comment]
On second thought, forget it, I think it's just best for me to hop on another distro instead of dealing with fedora.

**Comment by DaVikingMan** [comment]
I'm not sure if this will help but I think that the issue here is that you're using nvidia driver 515 which doesn't support your gpu. You would have to download a driver version from rpmfusion that supports your gpu(although I'm not sure if that is available in the rpmfusion repos)

**Comment by DaVikingMan** [comment]
Nvidia version 340 should work on your gpu
