### ISSUE TITLE
Balckscreen before loading Ubuntu 22

### ISSUE THREAD

**Issue by belafdil-chakib** [geminis3/envycontrol#65]
Linux distribution : Ubuntu 22.04
Nvidia driver version 57x
EnvyControl version 2.1.1

After using envycontrol to Switch to integrated mode my laptop wont display anything after grub and before login. 

I have a 15ach6h Lenovo légion 5 with rtx 3060. 

Do yoi have a workaround in order to ger back my data at least ?

**Comment by geminis3** [comment]
Are you sure your Legion isn't on dGPU mode (from BIOS)? If you want to use
envycontrol you need to use MSHybrid mode / Optimus

**Comment by belafdil-chakib** [comment]
It solved my problem. Thanks

**Comment by fuzunspm** [comment]
I had the same problem on fedora. I switched to switchable graphics on bios but still booting in to black screen. I switched to integrated mode before last reboot and now it won't boot

**Comment by bayasdev** [comment]
What device are you using?

**Comment by fuzunspm** [comment]
lenovo legion with amd cpu and nvidia gpu

**Comment by bayasdev** [comment]
You're better off using the built-in Mux switch in that case. Also, if you
don't provide logs, I can't help further.

Regards.

**Comment by fuzunspm** [comment]
I can't provide logs because I can't login, by built-in Mux switch you mean FN+Q keybind?
