### ISSUE TITLE
Is there a revert back script?

### ISSUE THREAD

**Issue by JDeepD** [geminis3/envycontrol#9]
The output of `nvidia-smi:`

```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

So it disabled all the nvidia kernal modules. How do I re enable them without disabling my integrated graphics modules? Basically, I want to revert back to the state before I used `envycontrol  --switch integrated`

**Comment by geminis3** [comment]
Try switching to hybrid mode.

**Comment by JDeepD** [comment]
Thanks
